CREATE USER atharva;

GRANT ALL PRIVILEGES ON DATABASE test_db TO atharva;


CREATE TABLE IF NOT EXISTS users(
id SERIAL PRIMARY KEY,
name VARCHAR(100),
email VARCHAR(100) UNIQUE,
age INTEGER,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS items(
id SERIAL PRIMARY KEY,
category VARCHAR(50) NOT NULL,   
name VARCHAR(50) NOT NULL,    
price NUMERIC(10, 2) NOT NULL
);